# .github/workflows/macos.yml
name: Run macOS in Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  macos-docker:
    runs-on: ubuntu-latest

    services:
      macos:
        image: dockurr/macos                           # Docker image chứa macOS
        env:                                           # Đặt biến môi trường cho service
          VERSION: "13"                                # macOS 13 Ventura
          DISK_SIZE: "128G"
          CPU_CORES: "4"
          RAM_SIZE: "8G"
        options: >-                                   # Thêm device và cap-add qua docker create options
          --device /dev/kvm
          --device /dev/net/tun
          --cap-add NET_ADMIN
        ports:
          - 8006:8006                                  # Mở port Web viewer
          - 5900:5900/tcp                              # Mở port VNC TCP
          - 5900:5900/udp                              # Mở port VNC UDP
        volumes:
          - ${{ github.workspace }}/macos:/storage      # Mount thư mục lưu trữ macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for macOS service to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 8006 && break
            echo "Waiting for macOS service..."
            sleep 5
          done

      - name: Display macOS web console URL
        run: echo "Access the macOS installer at http://localhost:8006"
