name: Start macOS Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  start-macos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Engine
        uses: docker/setup-docker-action@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Launch macOS container with Docker Compose
        run: docker compose -f macos.yml up -d

      - name: Show container status
        run: docker ps

      - name: Output service link
        run: |
          PORT=$(docker compose port <service_name> <container_port> | cut -d: -f2)
          echo "🔗 Service is running at: http://localhost:$PORT"