# .github/workflows/start.yaml
name: Start macOS Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  start-macos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3                 # Lấy code về runner :contentReference[oaicite:15]{index=15}

      - name: Set up Docker Engine
        uses: docker/setup-docker-action@v4       # Cài Docker Engine/CLI :contentReference[oaicite:16]{index=16}

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1      # Cài Compose V2 plugin :contentReference[oaicite:17]{index=17}

      - name: Launch macOS container with Docker Compose
        run: docker compose -f macos.yml up -d    # Dùng 'docker compose' thay vì 'docker-compose' :contentReference[oaicite:18]{index=18}
